# Generated by Django 5.0.1 on 2024-02-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=250)),
                ("task_desc", models.CharField(max_length=250)),
                ("date_created", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
