# Generated by Django 5.0.1 on 2024-02-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
