# Generated by Django 5.0.1 on 2024-02-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapp", "0002_task_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="image",
            field=models.ImageField(
                default="Image/None/Noimage.jpg", upload_to="Images/"
            ),
        ),
    ]
